### ISSUE TITLE
Remove Plane Finder

### ISSUE THREAD

**Issue by leearmstrong** [fcrohas/node-radar#1]
Not cool to steal data.

Please remove.

**Comment by fcrohas** [comment]
Ok done removed my code. https://github.com/fcrohas/node-radar/commits/master
Sorry for this.

**Comment by leearmstrong** [comment]
👍

**Comment by fcrohas** [comment]
My idea was not to steal data but to avoid quering your website too often... so i saved only some. The Api was quite easy to use.

Sorry again.
